#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const { root, home, plugins, exists, files, digest } = require('./managed');
const marker = '.agentic-dotnet-managed.json';

function snapshot(source) {
  return Object.fromEntries(files(source).filter(name => name !== marker).map(name => [name, digest(path.join(source, name))]));
}

function matches(destination, expected) {
  try { return JSON.stringify(snapshot(destination)) === JSON.stringify(expected); } catch { return false; }
}

function deploy(source, destination, backup) {
  const desired = snapshot(source);
  if (exists(destination)) {
    const stat = fs.lstatSync(destination);
    if (stat.isSymbolicLink()) {
      const target = path.resolve(path.dirname(destination), fs.readlinkSync(destination));
      if (target !== path.resolve(source)) { throw new Error('Unrelated plugin link: ' + destination); }
    } else {
      const record = path.join(destination, marker);
      if (!fs.existsSync(record)) { throw new Error('Unmanaged plugin directory: ' + destination); }
      const previous = JSON.parse(fs.readFileSync(record, 'utf8'));
      if (previous.source !== path.resolve(source) || !matches(destination, previous.files)) {
        throw new Error('Modified plugin deployment: ' + destination);
      }
      if (matches(destination, desired)) { return 'unchanged'; }
    }
  }
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  const staging = fs.mkdtempSync(path.join(path.dirname(destination), '.agentic-stage-'));
  try {
    fs.cpSync(source, staging, { recursive: true });
    fs.writeFileSync(path.join(staging, marker), JSON.stringify({ source: path.resolve(source), files: desired }, null, 2) + '\n');
    if (exists(destination)) {
      fs.mkdirSync(backup, { recursive: true });
      // Move the exact deployment. This preserves links without following their targets.
      const saved = path.join(backup, path.basename(destination));
      if (exists(saved)) { throw new Error('Backup already exists: ' + saved); }
      try { fs.renameSync(destination, saved); } catch (error) {
        if (error.code !== 'EXDEV') { throw error; }
        fs.cpSync(destination, saved, { recursive: true, verbatimSymlinks: true, errorOnExist: true, force: false });
        if (fs.lstatSync(destination).isSymbolicLink()) { fs.unlinkSync(destination); }
        else { fs.rmSync(destination, { recursive: true }); }
      }
    }
    fs.renameSync(staging, destination);
    return 'deployed';
  } finally {
    if (fs.existsSync(staging)) { fs.rmSync(staging, { recursive: true }); }
  }
}

function generate(directory = root) {
  const text = fs.readFileSync(path.join(directory, 'instructions/global.md'), 'utf8');
  const rule = '---\ndescription: Shared coding instructions and task-based skill selection\nalwaysApply: true\n---\n\n<!-- Generated by agentic-dotnet. Edit instructions/global.md. -->\n\n' + text;
  const destination = path.join(directory, 'adapters/cursor/rules/global-dotnet.mdc');
  if (!fs.existsSync(destination) || fs.readFileSync(destination, 'utf8') !== rule) {
    fs.writeFileSync(destination, rule);
  }
}

function sources(directory = root, userHome = home) {
  const cache = path.join(userHome, '.cache/agentic-dotnet/dotnet-skills/plugins');
  return [['agentic-dotnet', path.join(directory, 'adapters/cursor')], ...plugins(directory).map(name => [name, path.join(cache, name)])];
}

function main() {
  generate();
  const backup = path.join(root, 'backups/cursor-' + new Date().toISOString().replace(/[:.]/g, '-'));
  for (const [name, source] of sources()) {
    if (!fs.existsSync(source)) { console.log('[cursor] WARN source unavailable: ' + name); continue; }
    try {
      const state = deploy(source, path.join(home, '.cursor/plugins/local', name), backup);
      console.log('[cursor] ' + state + ': ' + name);
    } catch (error) {
      console.error('[cursor] ' + error.message);
      process.exitCode = 1;
    }
  }
}

if (require.main === module) { main(); }
module.exports = { deploy, generate, sources, snapshot, matches, marker };
