#!/usr/bin/env bash
set -euo pipefail

USER_HOME="${HOME:?HOME is required}"
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
ROOT_DIR="${AGENTIC_DOTNET_HOME:-$(cd "${SCRIPT_DIR}/.." && pwd -P)}"
GLOBAL_INSTRUCTIONS="${ROOT_DIR}/instructions/global.md"
BACKUP_DIR="${ROOT_DIR}/backups/sync-$(date '+%Y-%m-%d-%H%M%S')"
WARNINGS=0
REPLACE_EXISTING="${AGENTIC_DOTNET_REPLACE_EXISTING:-0}"

note() { printf '[sync] %s\n' "$*"; }
warn() { printf '[sync] WARN: %s\n' "$*" >&2; WARNINGS=$((WARNINGS + 1)); }

backup_path() {
  local path="$1"
  [ -e "$path" ] || [ -L "$path" ] || return 0
  local relative="${path#/}"
  mkdir -p "${BACKUP_DIR}/$(dirname "$relative")"
  cp -a "$path" "${BACKUP_DIR}/${relative}"
}

ensure_symlink() {
  local target="$1" link="$2"
  mkdir -p "$(dirname "$link")"
  if [ -L "$link" ] && [ "$(readlink "$link")" = "$target" ]; then
    note "ok symlink $link"
    return 0
  fi
  if [ -e "$link" ] || [ -L "$link" ]; then
    backup_path "$link"
    if [ -L "$link" ]; then
      rm "$link"
    elif [ "$REPLACE_EXISTING" = "1" ]; then
      rm -rf "$link"
    else
      warn "left unrelated regular path in place: $link"
      return 0
    fi
  fi
  ln -s "$target" "$link"
  note "linked $link -> $target"
}

ensure_managed_file() {
  local source="$1" destination="$2" marker="$3"
  mkdir -p "$(dirname "$destination")"
  if [ -f "$destination" ] && cmp -s "$source" "$destination"; then
    note "ok file $destination"
    return 0
  fi
  if [ -e "$destination" ] && ! grep -Fq "$marker" "$destination" 2>/dev/null; then
    backup_path "$destination"
    if [ "$REPLACE_EXISTING" = "1" ]; then
      rm -rf "$destination"
    else
      warn "left unrelated file in place: $destination"
      return 0
    fi
  fi
  local temporary
  temporary=$(mktemp "${destination}.tmp.XXXXXX")
  cp "$source" "$temporary"
  mv "$temporary" "$destination"
  note "updated $destination"
}

[ -f "$GLOBAL_INSTRUCTIONS" ] || { printf 'missing %s\n' "$GLOBAL_INSTRUCTIONS" >&2; exit 1; }
mkdir -p "${ROOT_DIR}/skills" "${USER_HOME}/.agents/skills" "${USER_HOME}/.claude/skills" "${USER_HOME}/.cursor/plugins/local" "${USER_HOME}/.copilot"

ensure_symlink "$GLOBAL_INSTRUCTIONS" "${USER_HOME}/.codex/AGENTS.md"
claude_adapter=$(mktemp "${TMPDIR:-/tmp}/agentic-dotnet-claude.XXXXXX")
printf '<!-- Managed by .agentic-dotnet; edit %s instead. -->\n@%s\n' "$GLOBAL_INSTRUCTIONS" "$GLOBAL_INSTRUCTIONS" > "$claude_adapter"
ensure_managed_file "$claude_adapter" "${USER_HOME}/.claude/CLAUDE.md" '.agentic-dotnet'
rm -f "$claude_adapter"
ensure_symlink "$GLOBAL_INSTRUCTIONS" "${USER_HOME}/.copilot/copilot-instructions.md"
ensure_symlink "${ROOT_DIR}/adapters/copilot/mcp-config.json" "${USER_HOME}/.copilot/mcp-config.json"
ensure_symlink "${ROOT_DIR}/adapters/cursor" "${USER_HOME}/.cursor/plugins/local/agentic-dotnet"

if [ -d "${USER_HOME}/.config/kilo" ]; then
  ensure_symlink "$GLOBAL_INSTRUCTIONS" "${USER_HOME}/.config/kilo/AGENTS.md"

  kilo_plugins=()
  while IFS= read -r plugin; do
    kilo_plugins+=("$plugin")
  done < <(awk '
    /^(core|standard|optional):/ { active=1; next }
    /^[A-Za-z_][A-Za-z0-9_-]*:/ { active=0 }
    active && /^[[:space:]]*-[[:space:]]+/ { sub(/^[[:space:]]*-[[:space:]]+/, ""); print }
  ' "${ROOT_DIR}/config/plugins.yaml")
  skills_paths=()
  for plugin in "${kilo_plugins[@]}"; do
    skills_paths+=("\"${USER_HOME}/.cache/agentic-dotnet/dotnet-skills/plugins/${plugin}/skills\"")
  done
  managed_prefix="${USER_HOME}/.cache/agentic-dotnet/dotnet-skills/plugins/"
  patch=$(printf '{"mcp":{"microsoft-learn":{"type":"remote","url":"https://learn.microsoft.com/api/mcp","enabled":true}},"skills":{"paths":[%s],"managedPrefix":"%s"}}' "$(IFS=,; printf '%s' "${skills_paths[*]}")" "$managed_prefix")
  if command -v node >/dev/null 2>&1; then
    if ! printf '%s' "$patch" | node "${ROOT_DIR}/scripts/kilo-config-merge.js" "${USER_HOME}/.config/kilo/kilo.jsonc" "$BACKUP_DIR"; then
      warn 'Kilo config merge failed'
    fi
  else
    warn 'node is required to merge Kilo config but was not found'
  fi
fi

temporary_rule=$(mktemp "${ROOT_DIR}/adapters/cursor/rules/global-dotnet.mdc.tmp.XXXXXX")
{
  printf '%s\n' '---' 'description: Shared coding instructions and task-based skill selection managed by ~/.agentic-dotnet' 'alwaysApply: true' '---' '' '<!-- Generated by ~/.agentic-dotnet/scripts/sync.sh; edit instructions/global.md instead. -->' ''
  cat "$GLOBAL_INSTRUCTIONS"
} > "$temporary_rule"
mv "$temporary_rule" "${ROOT_DIR}/adapters/cursor/rules/global-dotnet.mdc"
note 'regenerated Cursor global rule'

for skill_dir in "${ROOT_DIR}"/skills/*; do
  [ -d "$skill_dir" ] || continue
  [ -f "$skill_dir/SKILL.md" ] || { warn "missing SKILL.md in $skill_dir"; continue; }
  skill_name=$(basename "$skill_dir")
  ensure_symlink "$skill_dir" "${USER_HOME}/.agents/skills/${skill_name}"
  ensure_symlink "$skill_dir" "${USER_HOME}/.claude/skills/${skill_name}"
done

for skills_root in "${USER_HOME}/.agents/skills" "${USER_HOME}/.claude/skills"; do
  find "$skills_root" -mindepth 1 -maxdepth 1 -type l -print0 2>/dev/null | while IFS= read -r -d '' link; do
    target=$(readlink "$link")
    case "$target" in
      "${ROOT_DIR}/skills/"*)
        if [ ! -e "$link" ]; then rm "$link"; note "removed stale managed link $link"; fi
        ;;
    esac
  done
done

if [ -d "$BACKUP_DIR" ] && find "$BACKUP_DIR" -mindepth 1 -print -quit | grep -q .; then
  note "completed with $WARNINGS warning(s); backup: $BACKUP_DIR"
else
  rmdir "$BACKUP_DIR" 2>/dev/null || true
  note "completed with $WARNINGS warning(s)"
fi
