#!/usr/bin/env bash
set -euo pipefail

USER_HOME="${HOME:?HOME is required}"
ROOT_DIR="${USER_HOME}/.agentic-dotnet"
GLOBAL_INSTRUCTIONS="${ROOT_DIR}/instructions/global.md"
BACKUP_DIR="${ROOT_DIR}/backups/sync-$(date '+%Y-%m-%d-%H%M%S')"
WARNINGS=0

note() { printf '[sync] %s\n' "$*"; }
warn() { printf '[sync] WARN: %s\n' "$*" >&2; WARNINGS=$((WARNINGS + 1)); }

backup_path() {
  local path="$1"
  [ -e "$path" ] || [ -L "$path" ] || return 0
  local relative="${path#/}"
  mkdir -p "${BACKUP_DIR}/$(dirname "$relative")"
  cp -a "$path" "${BACKUP_DIR}/${relative}"
}

ensure_symlink() {
  local target="$1" link="$2"
  mkdir -p "$(dirname "$link")"
  if [ -L "$link" ] && [ "$(readlink "$link")" = "$target" ]; then
    note "ok symlink $link"
    return 0
  fi
  if [ -e "$link" ] || [ -L "$link" ]; then
    backup_path "$link"
    if [ -L "$link" ]; then
      rm "$link"
    else
      warn "left unrelated regular path in place: $link"
      return 0
    fi
  fi
  ln -s "$target" "$link"
  note "linked $link -> $target"
}

ensure_managed_file() {
  local source="$1" destination="$2" marker="$3"
  mkdir -p "$(dirname "$destination")"
  if [ -f "$destination" ] && cmp -s "$source" "$destination"; then
    note "ok file $destination"
    return 0
  fi
  if [ -e "$destination" ] && ! grep -Fq "$marker" "$destination" 2>/dev/null; then
    backup_path "$destination"
    warn "left unrelated file in place: $destination"
    return 0
  fi
  local temporary
  temporary=$(mktemp "${destination}.tmp.XXXXXX")
  cp "$source" "$temporary"
  mv "$temporary" "$destination"
  note "updated $destination"
}

[ -f "$GLOBAL_INSTRUCTIONS" ] || { printf 'missing %s\n' "$GLOBAL_INSTRUCTIONS" >&2; exit 1; }
mkdir -p "${ROOT_DIR}/skills" "${USER_HOME}/.agents/skills" "${USER_HOME}/.claude/skills" "${USER_HOME}/.cursor/plugins/local" "${USER_HOME}/.copilot"

ensure_symlink "$GLOBAL_INSTRUCTIONS" "${USER_HOME}/.codex/AGENTS.md"
ensure_managed_file "${ROOT_DIR}/adapters/claude/CLAUDE.md" "${USER_HOME}/.claude/CLAUDE.md" '.agentic-dotnet'
ensure_symlink "$GLOBAL_INSTRUCTIONS" "${USER_HOME}/.copilot/copilot-instructions.md"
ensure_symlink "${ROOT_DIR}/adapters/copilot/mcp-config.json" "${USER_HOME}/.copilot/mcp-config.json"
ensure_symlink "${ROOT_DIR}/adapters/cursor" "${USER_HOME}/.cursor/plugins/local/agentic-dotnet"

temporary_rule=$(mktemp "${ROOT_DIR}/adapters/cursor/rules/global-dotnet.mdc.tmp.XXXXXX")
{
  printf '%s\n' '---' 'description: Canonical global .NET and C# agent instructions managed by ~/.agentic-dotnet' 'alwaysApply: true' '---' '' '<!-- Generated by ~/.agentic-dotnet/scripts/sync.sh; edit instructions/global.md instead. -->' ''
  cat "$GLOBAL_INSTRUCTIONS"
} > "$temporary_rule"
mv "$temporary_rule" "${ROOT_DIR}/adapters/cursor/rules/global-dotnet.mdc"
note 'regenerated Cursor global rule'

for skill_dir in "${ROOT_DIR}"/skills/*; do
  [ -d "$skill_dir" ] || continue
  [ -f "$skill_dir/SKILL.md" ] || { warn "missing SKILL.md in $skill_dir"; continue; }
  skill_name=$(basename "$skill_dir")
  ensure_symlink "$skill_dir" "${USER_HOME}/.agents/skills/${skill_name}"
  ensure_symlink "$skill_dir" "${USER_HOME}/.claude/skills/${skill_name}"
done

for skills_root in "${USER_HOME}/.agents/skills" "${USER_HOME}/.claude/skills"; do
  find "$skills_root" -mindepth 1 -maxdepth 1 -type l -print0 2>/dev/null | while IFS= read -r -d '' link; do
    target=$(readlink "$link")
    case "$target" in
      "${ROOT_DIR}/skills/"*)
        if [ ! -e "$link" ]; then rm "$link"; note "removed stale managed link $link"; fi
        ;;
    esac
  done
done

if [ "$WARNINGS" -gt 0 ]; then
  note "completed with $WARNINGS warning(s); backup: $BACKUP_DIR"
else
  rmdir "$BACKUP_DIR" 2>/dev/null || true
  note 'completed'
fi

